language: generic
sudo: required
before_script:
- sudo apt-get remove --purge docker-engine
- curl -fsSL https://get.docker.com/ | sh
- sudo curl -L -o /usr/local/bin/opctl https://github.com/opctl/cli/releases/download/0.1.0/opctl-linux-x86_64
- sudo chmod +x /usr/local/bin/opctl
services:
- docker
script:
- opctl run -a CODECOV_TOKEN -a GIT_BRANCH=$TRAVIS_BRANCH release
