language: generic
sudo: required
before_script:
- curl -L https://bin.equinox.io/c/5Sox3KYDRTV/opctl-alpha-linux-amd64.tgz | sudo tar -xzv -C /usr/local/bin
services:
- docker
script:
- opctl run -a gitBranch=$TRAVIS_BRANCH build
