version: "2"
services:
  publish-coverage-to-codecov:
    extends:
      service: working_dir
      file: ../.common/docker-compose.yml
    build: ./
    environment:
      - CODECOV_TOKEN
    entrypoint: .opspec/publish-coverage-to-codecov/entrypoint.sh
