description: deploys the website
name: website/deploy
inputs:
  srcDir:
    dir:
      default: .
      description: dir containing the doc source
  AWS_ACCESS_KEY_ID:
    string:
      constraints: { minLength: 20 }
      description: access key for AWS
  AWS_SECRET_ACCESS_KEY:
    string:
      constraints: { minLength: 20 }
      description: secret access key for AWS
      isSecret: true
run:
  serial:
    - op:
        pkg: { ref: compile }
        inputs: { srcDir }
        outputs: { srcDir }
    - container:
        cmd:
          - sh
          - -ce
          - |
            echo "installing deps"
            pip install awscli

            echo "deploy"
            aws s3 sync . s3://opctl.io --delete
        dirs:
          /src: srcDir
        envVars:
          AWS_ACCESS_KEY_ID:
          AWS_SECRET_ACCESS_KEY:
          AWS_DEFAULT_REGION: us-west-2
        image: { ref: 'python:2.7' }
        workDir: /src/build
